import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            colors: {
                primary: '#0056a4',
                'primary-container': '#006ecf',
                'primary-fixed': '#d5e3ff',
                'primary-fixed-dim': '#a7c8ff',
                'on-primary': '#ffffff',
                'on-primary-fixed': '#001b3c',
                'on-primary-fixed-variant': '#004788',
                'on-primary-container': '#eef2ff',
                'inverse-primary': '#a7c8ff',
                secondary: '#376093',
                'secondary-container': '#9fc6ff',
                'secondary-fixed': '#d4e3ff',
                'secondary-fixed-dim': '#a4c9ff',
                'on-secondary': '#ffffff',
                'on-secondary-container': '#275284',
                'on-secondary-fixed': '#001c39',
                'on-secondary-fixed-variant': '#1b487a',
                tertiary: '#8f3d00',
                'tertiary-container': '#b55002',
                'tertiary-fixed': '#ffdbca',
                'tertiary-fixed-dim': '#ffb68f',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#ffeee8',
                'on-tertiary-fixed': '#331100',
                'on-tertiary-fixed-variant': '#773200',
                surface: '#f7f9fb',
                'surface-dim': '#d8dadc',
                'surface-bright': '#f7f9fb',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f2f4f6',
                'surface-container': '#eceef0',
                'surface-container-high': '#e6e8ea',
                'surface-container-highest': '#e0e3e5',
                'surface-variant': '#e0e3e5',
                'surface-tint': '#005eb2',
                'on-surface': '#191c1e',
                'on-surface-variant': '#414752',
                'inverse-surface': '#2d3133',
                'inverse-on-surface': '#eff1f3',
                'on-background': '#191c1e',
                background: '#f7f9fb',
                outline: '#717784',
                'outline-variant': '#c1c6d5',
                error: '#ba1a1a',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                'on-error-container': '#93000a',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Inter', ...defaultTheme.fontFamily.sans],
                body: ['Inter', ...defaultTheme.fontFamily.sans],
                label: ['Inter', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
